### ISSUE TITLE
소스코드 히스토리

### ISSUE THREAD

**Issue by hackmod** [Hdactech/hdac#1]
블록체인 소스도 공개하지 않고 메인넷을?

이런 아마추어적인 행태를 현대라는 이름을 걸고 했다는 것이 너무나 우스꽝 스럽습니다.

작동하는 소스를 올려주시기 바랍니다. 잘못된 부분은 차차 고치면 됩니다. 그것이 github가 있는 이유입니다.
소스도 공개하지 않은채로 메인넷이 돌아가는 코인은 스캠과 다를바 없습니다.
조속한 소스 공개를 부탁드립니다.

기타 참고 사항
https://steemit.com/kr/@atomrigs/hdac

**Comment by hackmod** [comment]
모든 히스토리가 담긴 별도의 소스코드 레포지터리를 별도로 관리하시는 것인가요?

왜 히스토리가 날아간 소스코드를 올리신 것인가요?

오리지널 소스코드는 multichain 같군요.

https://github.com/MultiChain/multichain

히스토리가 모두 담겨있는 소스코드를 별도로 관리하지 마시고 모두 올려주시기 바랍니다.

https://steemit.com/kr/@hackyminer/hdac-source-code-released

**Comment by hackmod** [comment]
https://github.com/OpenCommunityCoin/hdac
아무 답변이 없으셔서 급하게 히스토리 살린 소스코드 올려봅니다.

혹시 오리지널 소스코드와 다르게 어떻게 고쳤는지 궁금하신 분은 위 소스코드 참고해 보시기 바랍니다.
다행스럽게(?) 멀티체인 소스코드가 많은 수정이 없는 상태라서, 멀티체인 개발진과 hdac 개발진이 고친부분이 섞여있을 수 있으나 대충은 어떤 부분을 고쳤는지 참고하실 수 있을 것입니다.

**Comment by ghost** [comment]
@hackmod 소스코드 히스토리는 의무사항이 아닌것으로 알고 있습니다.

**Comment by jungpilyu** [comment]
GPLv3 인경우 다음과 같이 되어 있습니다.
"Changes made to codes must be documented"
즉 원래 소스인 멀티체인 소스코드에서 변경된 사항은 문서화하여 공개하여야 합니다.
다시말하면 소스코드 히스토리는 의무사항이며 
따라서 엄밀히 말하면 현재 멀티체인 소스코드의 GPLv3 라이센스를 위반한 상황입니다.

**Comment by sobae** [comment]
Thank you for your advice.
