### ISSUE TITLE
I propose HIP(Hdac Improvement Proposal).

### ISSUE THREAD

**Issue by totoro7850** [Hdactech/hdac#10]
Hi. I am John.

I'm Hdac investor and developer.

I'm interested in blockchain and I'm looking some blockchain platform.

Is there no proposal document for this place?

There are some suggestions for bitcoin: (Bitcoin Improvement Proposal)
https://github.com/bitcoin/bips

Most coins have documented their own proposals
zcash: zip, dash: dip, ethereum: eip etc...

I suggest you document proposals of Hdac.

Hdac address: H8hnyGxcECfvdxTVForTpy2oquN9Qx4LJM

**Comment by HdacTechTeam** [comment]
Hello, this is Hdac Technology.

Thanks for the suggestion.
This also has been considered from our-side as well.

We gave you a small compensation.

Thanks.
