### ISSUE TITLE
1.08.6 build broken on windows

### ISSUE THREAD

**Issue by sebastianbassen** [Hdactech/hdac#11]
The current 1.08.6 tag won't build on ubuntu with mingw. It seems serialize.h needs to include https://github.com/bitcoin/bitcoin/blob/master/src/compat/endian.h

**Comment by sebastianbassen** [comment]
I've opened a PR https://github.com/Hdactech/hdac/pull/12. I'm no C++ dev but it builds and runs fine on windows 10

**Comment by sobae** [comment]
I'm sorry I did not check the build with mingw.
your pull request was merged & commit in master branch.
Thanks for your help.
