### ISSUE TITLE
[Question] about hdacd-cold

### ISSUE THREAD

**Issue by lambda2003** [Hdactech/hdac#13]
I know it is not the right place to ask a question. Sorry.. but I don't know where to ask? 

My question -
As I see core's help description, 
hdac-util seems that it helps to create configuration file. 
hdacd-cold is offline daemon?? What is this for?? 

After unzipped(tar) 1.08.6, I could see "hdacd-cold" and "hdac-util". What is the purpose of hdacd-cold??
Is there any place(URL?) to check the document or description of hdacd-cold and hdac-util??

Thank you,

**Comment by sobae** [comment]
hdac-cold is used as a means of verifying transactions on offline.
It is used for testing purposes only. 
hdac-util is for the same purpose.
