### ISSUE TITLE
[BUG] send command error.

### ISSUE THREAD

**Issue by lambda2003** [Hdactech/hdac#14]
I installed Hdac core1.08.6(latest version) in ubuntu.

Command: hdac-cli hdac send [To Address] amount
My balance is higher than the amount I tried to send. 

My issue:
1. I sent 100,000 to a address. 
2. I sent 100,000 a few times to the same address.
3. Then I got below error. 
error code: -6
error message: Change address not found

Sometimes I got below
error code: -8
error message: Change address not found

My question.
1. What is the error message mean? 
2. Is it a bug or how I can resolve my issue ?? 

Thank you,

**Comment by sobae** [comment]
"error code: -6 " is "Not enough funds in wallet".
"error code:-8" is "Invalid, missing or duplicate parameter".

Was there same problem with ver-1.08.0 ?
Can you check this problem with 1.08.0 ?
Please attach the debug.log  that is in  " ~/.hdac/hdac/debug.log " 
( version 1.08.6 and 1.08.0 )

**Comment by lambda2003** [comment]
sorry... I can't share it with public. If you give me an email address, I can send my debug.log file and my issue with captured images. Anyway, my email address is lambda2003 .at. gmail .dot. com

Thank you,

**Comment by sobae** [comment]
need to change debug level.
please run  this command  -->  " hdac-cli hdac setruntimeparam debug 5 "
My e-mail is namynez@gmail.com
Please let me know the timestamp of your testing.

**Comment by sobae** [comment]
answered via email.
