### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by gloomik** [Hdactech/hdac#15]
Hello!

How i can run Hdac wallet in testnet?

**Comment by HdacTech** [comment]
Create a testnet node
Connect to testnet seed, mined to gen=1 mode, mined and node wallet is created starting with lowercase h

Ubuntu 16.04.1 LTS
$ wget https://github.com/hdactech/hdac/releases/download/1.08.6/hdac-1.08.6_linux_x64.tar.gz
$ tar xvf hdac-1.08.6_linux_x64.tar.gz
$ mkdir bin
$ mv hdac* bin
$ hdacd hdac-testnet@testseed.as.hdactech.com:18823 -gen=1 -daemon
$ hdac-cli hdac-testnet getinfo
$ hdac-cli hdac-testnet listaddresses
$ hdac-cli hdac-testnet getbalance
$ tail -f .hdac/hdac-testnet/debug.log
