### ISSUE TITLE
I am trying to install  hdac coin 

### ISSUE THREAD

**Issue by lettertoamit** [Hdactech/hdac#3]
What i am facing is this issue 
$HOME/hdac/src/./hdac-cli hdac getinfo
{"method":"getinfo","params":[],"id":1,"chain_name":"hdac"}

error: incorrect rpcuser or rpcpassword (authorization failed)
root@01:~/.hdac/getinfo# $HOME/hdac/src/./hdac-cli hdac getinfo

can any one please help me.

**Comment by HdacTech** [comment]
sorry for late reply.

There are some things to check.
1.  check your data folder
   --> If you have a previous history of running the daemon, you should have data folder. ( maybe,  $HOME/.hdac/hdac )
2.   check your daemon --> " ps aux | grep hdac "

3.  check your system port number 
    --> If the port used by the daemon is already in use.  
           otherwise, check firewall of your system
