### ISSUE TITLE
여기에 지갑에 관련된 이슈 적어도 되나요??

### ISSUE THREAD

**Issue by nzmotion** [Hdactech/hdac#4]
지갑에서 보내기 할때
1.주소를 입력하면 올바른 주소인지 먼저 체크해서 안내문구가 떴음 좋겠구요

2.전송수수료에 관한 가이드 또는 보낼 수량을 체크해서 자동으로 미니멈으로 들어가면 좋을것 같네요

사용하기 너무 불편해요 몇개를 입력해야하는지도 모르겠구요 숫자를 조금씩 올려보면서 보낼수 있는지 체크해야 하는 부분이 사용자에게 너무 피곤하네요

**Comment by HdacTechTeam** [comment]
좋은 의견 주셔서 감사드립니다.
다음 지갑 업데이트 시 의견 참고하도록 하겠습니다.
지갑 관련하여 별도의 repository 가 있으니 그 쪽에 의견 남겨 주시면 좋을 것 같습니다.
( https://github.com/Hdactech/HdacPcWallet )
감사합니다.
