### ISSUE TITLE
Change the algorithm from POW to POS

### ISSUE THREAD

**Issue by zemelax** [Hdactech/hdac#6]
why do not you want to change the algorithm? Or add POS algorithm. So people who have coins do not have a strong desire to sell them at once. The coin holders will have an incentive, keep coins, so you increase the coinage. Or is this not possible?  
I also wanted to note that the transaction speed seemed to me not too high (

My Hdac address: HHjwBVdUgmWVktKNB3eidxa2rsQU7wZP6v
Telegram: @DS_1986

**Comment by HdacTechTeam** [comment]
Hello, this is Hdac Technology.

Thanks for the suggestion.
This also has been considered from our-side as well. 

We will give a small compensation soon.

Thanks.
