### ISSUE TITLE
Reduction of block rewards, Miners, PoS Algorithm, ASICs

### ISSUE THREAD

**Issue by AdTokens** [Hdactech/hdac#8]
**Reduction of block rewards**
I've compared many crypto currencies in the market. As a result of the statistics I obtained, I decided that Hdac's block rewards should be reduced.

[Reduction of block rewards](https://docs.google.com/spreadsheets/d/1-KKyP-hK-3K0NbDXlTfZtPcAlzo84ejwUtqttuQjw4w/edit?usp=sharing)

- Hdac has 13x more block rewards than Bitcoin.
- Hdac has 7.8x more block rewards than Ethereum.
- Hdac has 5,5x more block rewards than Litecoin.
- Hdac has 8.8x more block rewards than Monero.
- Hdac has 6x more block rewards than Dash.
- Hdac has 5.8x more block rewards than Ethereum Classic.

The high block reward will result in inflation. If we calculate Hdac's block reward according to the average Hdac's block reward shouldn't exceed 300,000 daily. 

- **If you ask me, Hdac's daily block reward should be reduced to at least 240,000**.

**Miners**
We created a list as a Turkish community and we think that some miners have manipulated Hdac price.

[Hdac Rich List](https://docs.google.com/spreadsheets/d/1qDk3yY8lx2U7rDuyibuZVim8rT8gURPOSH03LzVEdX0/edit?usp=sharing)

The biggest reason for Hdac's price decrease is the high block rewards. Some miners have a very high amount of Hdac. Such as;

[50 Million Tokens - H7tX1eBtawayqkmNwzfQgE9cs8DL6uBUaQ](https://explorer.as.hdactech.com/hdac-explorer/address/H7tX1eBtawayqkmNwzfQgE9cs8DL6uBUaQ)
[28 Million Tokens - HERtkDYb9qtP3Hx6eGa1WJjXETjCobTjtq](https://explorer.as.hdactech.com/hdac-explorer/address/HERtkDYb9qtP3Hx6eGa1WJjXETjCobTjtq)
[21 Million Tokens - HS39PwAP2shdockeaddPCBYP9FxU6FPEAR](https://explorer.as.hdactech.com/hdac-explorer/address/HS39PwAP2shdockeaddPCBYP9FxU6FPEAR)
[19 Million Tokens - HJ2mxPFTx4gz9anVA1oMmJTeBb3NXkoDDV](https://explorer.as.hdactech.com/hdac-explorer/address/HJ2mxPFTx4gz9anVA1oMmJTeBb3NXkoDDV)

**ePoW to PoS and %51 Attack**
You need to reduce block rewards, but after reducing Hdac block rewards, Hashrate will decrease. A low hashrate may cause an 51% attack. To prevent this, Hdac must change from the ePoW algorithm to the PoS algorithm.

**ASIC Miners**
The PoS algorithm protects Hdac against ASIC Miner.

**### We can make Hdac great again.**
These are the easiest way to increase the Hdac's price and ensure the safety of the Hdac blockchain.

**Hdac address:** HPFDgKQeFXdkzxfY4EgHD3WcWy8pdrEWLi
**Telegram:** @XhearthmeagN

**Comment by HdacTechTeam** [comment]
Hello, this is Hdac Technology.

Thanks for the suggestion.
This also has been considered from our-side as well.

We gave you a small compensation.

Thanks.

**Comment by enfarktus** [comment]
The "Delayed Proof of Work" mechanism, which Komodo uses, offers a solution especially for 51% attack. Hdac will be more healthy to pass to this system. For your review, I share some articles about "Delayed Proof of Work": 
- https://steemit.com/komodo/@komodoplatform/komodo-zcash-pow-with-dpow-consensus-mechanism
- https://github.com/SuperNETorg/komodo/wiki/Delayed-Proof-of-Work-(dPoW)-Whitepaper
- https://komodoplatform.com/security-delayed-proof-of-work-dpow/
