### ISSUE TITLE
About 51% attack!

### ISSUE THREAD

**Issue by enfarktus** [Hdactech/hdac#9]
The "Delayed Proof of Work" mechanism, which Komodo uses, offers a solution especially for 51% attack. Hdac will be more healthy to pass to this system. For your review, I share some articles about "Delayed Proof of Work":

- https://steemit.com/komodo/@komodoplatform/komodo-zcash-pow-with-dpow-consensus-mechanism
- https://github.com/SuperNETorg/komodo/wiki/Delayed-Proof-of-Work-(dPoW)-Whitepaper
- https://komodoplatform.com/security-delayed-proof-of-work-dpow/

Hdac: H7tHsyEpDVW5jSQ5TmSMCvdjrh8kiSSe7Z
Telegram: @enfarktus

**Comment by HdacTechTeam** [comment]
Hello, This is Hdactech. 

Thanks for your opinion; however, the algorithm has already been suggested and now under a internal review. 

If you can be more specific in regards to the idea you shared with us, then this will help us review it. 

Thanks.
